import { useEffect, useRef, useState, type ButtonHTMLAttributes, type ReactNode } from 'react';
export function Icon({name='arrow',size=20}:{name?:string | undefined;size?:number}){
 const paths:Record<string,ReactNode>={arrow:<><path d="M4 12h15m-6-6 6 6-6 6"/></>,phone:<path d="m7 3 3 5-3 3c2 3 3 4 6 6l3-3 5 3c0 3-2 5-5 4C8 19 4 15 3 8 2 5 4 3 7 3Z"/>,pin:<><path d="M19 10c0 5-7 11-7 11S5 15 5 10a7 7 0 1 1 14 0Z"/><circle cx="12" cy="10" r="2"/></>,shield:<><path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6l8-3Z"/><path d="m8 12 3 3 5-6"/></>,heart:<path d="M12 20 4 12C-2 5 7 1 12 7c5-6 14-2 8 5l-8 8Z"/>,book:<><path d="M12 5v16M3 4c4-1 6 0 9 2 3-2 5-3 9-2v15c-4-1-6 0-9 2-3-2-5-3-9-2V4Z"/></>,sun:<><circle cx="12" cy="12" r="4"/><path d="M12 1v3m0 16v3M1 12h3m16 0h3M4 4l2 2m12 12 2 2M4 20l2-2M18 6l2-2"/></>,menu:<path d="M4 6h16M4 12h16M4 18h16"/>,close:<path d="m6 6 12 12M6 18 18 6"/>,check:<path d="m5 12 4 4L19 6"/>,eye:<><path d="M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/></>,edit:<><path d="m15 4 5 5-11 11H4v-5L15 4Z"/><path d="m12 7 5 5"/></>,trash:<><path d="M3 6h18M9 6V3h6v3M6 6l1 15h10l1-15M10 10v7m4-7v7"/></>,plus:<path d="M12 4v16M4 12h16"/>,clock:<><circle cx="12" cy="12" r="9"/><path d="M12 6v6l4 2"/></>,mail:<><rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 6 9 7 9-7"/></>,leaf:<><path d="M4 20C2 5 9 3 21 3c0 13-7 18-17 17Z"/><path d="m4 20 12-12"/></>,grid:<><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/></>};
 return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]||paths['arrow']}</svg>;
}
export function Button({children,variant='primary',className='',...props}:ButtonHTMLAttributes<HTMLButtonElement>&{variant?:'primary'|'secondary'|'plain'|'danger'|'icon'}){return <button {...props} className={`btn btn-${variant} ${className}`}>{children}</button>;}
export function Photo({src,alt,className='',eager=false}:{src?:string | undefined;alt:string;className?:string;eager?:boolean}){const [failed,setFailed]=useState(false);useEffect(()=>setFailed(false),[src]);return failed||!src?<div className={`photo-fallback ${className}`} role="img" aria-label={alt}><Icon name="sun" size={36}/><span>Clay N Potter</span></div>:<img src={src} alt={alt} className={className} loading={eager?'eager':'lazy'} onError={()=>setFailed(true)}/>;}
export function Modal({children,onClose,title,wide=false}:{children:ReactNode;onClose:()=>void;title:string;wide?:boolean}){const ref=useRef<HTMLDivElement>(null);useEffect(()=>{const previous=document.activeElement as HTMLElement|null;const overflow=document.body.style.overflow;document.body.style.overflow='hidden';ref.current?.focus();function key(e:KeyboardEvent){if(e.key==='Escape')onClose();if(e.key==='Tab'){const elements=ref.current?.querySelectorAll<HTMLElement>('button,a[href],input,select,textarea');if(!elements?.length)return;const first=elements[0],last=elements[elements.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}}document.addEventListener('keydown',key);return()=>{document.body.style.overflow=overflow;document.removeEventListener('keydown',key);previous?.focus();};},[onClose]);return <div className="modal-backdrop" onClick={onClose}><div className={`modal ${wide?'modal-wide':''}`} role="dialog" aria-modal="true" aria-label={title} tabIndex={-1} ref={ref} onClick={e=>e.stopPropagation()}><div className="modal-head"><h2>{title}</h2><Button variant="icon" aria-label="Close dialog" onClick={onClose}><Icon name="close"/></Button></div>{children}</div></div>;}
export function SectionHeading({eyebrow,title,description,children}:{eyebrow:string;title:string;description?:string;children?:ReactNode}){return <div className="section-heading"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2>{description&&<p>{description}</p>}</div>{children}</div>;}
export function Stars({rating=5}:{rating?:number}){return <span className="stars" aria-label={`${rating} out of 5 stars`}>{'★'.repeat(rating)}{'☆'.repeat(5-rating)}</span>;}
