/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DayCareRouteImport } from './routes/day-care'
import { Route as FacilitiesRouteImport } from './routes/facilities'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as PlaySchoolRouteImport } from './routes/play-school'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as AdminActivitiesRouteImport } from './routes/admin.activities'
import { Route as AdminAdmissionsRouteImport } from './routes/admin.admissions'
import { Route as AdminContactInformationRouteImport } from './routes/admin.contact-information'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminEnquiriesRouteImport } from './routes/admin.enquiries'
import { Route as AdminFacilitiesRouteImport } from './routes/admin.facilities'
import { Route as AdminGalleryRouteImport } from './routes/admin.gallery'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminProgramsRouteImport } from './routes/admin.programs'
import { Route as AdminTestimonialsRouteImport } from './routes/admin.testimonials'
import { Route as AdminWebsiteSettingsRouteImport } from './routes/admin.website-settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DayCareRoute = DayCareRouteImport.update({
  id: '/day-care',
  path: '/day-care',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilitiesRoute = FacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaySchoolRoute = PlaySchoolRouteImport.update({
  id: '/play-school',
  path: '/play-school',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminActivitiesRoute = AdminActivitiesRouteImport.update({
  id: '/admin/activities',
  path: '/admin/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdmissionsRoute = AdminAdmissionsRouteImport.update({
  id: '/admin/admissions',
  path: '/admin/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContactInformationRoute = AdminContactInformationRouteImport.update({
  id: '/admin/contact-information',
  path: '/admin/contact-information',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEnquiriesRoute = AdminEnquiriesRouteImport.update({
  id: '/admin/enquiries',
  path: '/admin/enquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFacilitiesRoute = AdminFacilitiesRouteImport.update({
  id: '/admin/facilities',
  path: '/admin/facilities',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/admin/gallery',
  path: '/admin/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProgramsRoute = AdminProgramsRouteImport.update({
  id: '/admin/programs',
  path: '/admin/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/admin/testimonials',
  path: '/admin/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWebsiteSettingsRoute = AdminWebsiteSettingsRouteImport.update({
  id: '/admin/website-settings',
  path: '/admin/website-settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activities': typeof ActivitiesRoute
  '/admissions': typeof AdmissionsRoute
  '/contact': typeof ContactRoute
  '/day-care': typeof DayCareRoute
  '/facilities': typeof FacilitiesRoute
  '/gallery': typeof GalleryRoute
  '/play-school': typeof PlaySchoolRoute
  '/programs': typeof ProgramsRoute
  '/testimonials': typeof TestimonialsRoute
  '/admin/activities': typeof AdminActivitiesRoute
  '/admin/admissions': typeof AdminAdmissionsRoute
  '/admin/contact-information': typeof AdminContactInformationRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/facilities': typeof AdminFacilitiesRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/website-settings': typeof AdminWebsiteSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activities': typeof ActivitiesRoute
  '/admissions': typeof AdmissionsRoute
  '/contact': typeof ContactRoute
  '/day-care': typeof DayCareRoute
  '/facilities': typeof FacilitiesRoute
  '/gallery': typeof GalleryRoute
  '/play-school': typeof PlaySchoolRoute
  '/programs': typeof ProgramsRoute
  '/testimonials': typeof TestimonialsRoute
  '/admin/activities': typeof AdminActivitiesRoute
  '/admin/admissions': typeof AdminAdmissionsRoute
  '/admin/contact-information': typeof AdminContactInformationRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/facilities': typeof AdminFacilitiesRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/website-settings': typeof AdminWebsiteSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activities': typeof ActivitiesRoute
  '/admissions': typeof AdmissionsRoute
  '/contact': typeof ContactRoute
  '/day-care': typeof DayCareRoute
  '/facilities': typeof FacilitiesRoute
  '/gallery': typeof GalleryRoute
  '/play-school': typeof PlaySchoolRoute
  '/programs': typeof ProgramsRoute
  '/testimonials': typeof TestimonialsRoute
  '/admin/activities': typeof AdminActivitiesRoute
  '/admin/admissions': typeof AdminAdmissionsRoute
  '/admin/contact-information': typeof AdminContactInformationRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/facilities': typeof AdminFacilitiesRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/website-settings': typeof AdminWebsiteSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/activities'
    | '/admissions'
    | '/contact'
    | '/day-care'
    | '/facilities'
    | '/gallery'
    | '/play-school'
    | '/programs'
    | '/testimonials'
    | '/admin/activities'
    | '/admin/admissions'
    | '/admin/contact-information'
    | '/admin/dashboard'
    | '/admin/enquiries'
    | '/admin/facilities'
    | '/admin/gallery'
    | '/admin/login'
    | '/admin/programs'
    | '/admin/testimonials'
    | '/admin/website-settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/activities'
    | '/admissions'
    | '/contact'
    | '/day-care'
    | '/facilities'
    | '/gallery'
    | '/play-school'
    | '/programs'
    | '/testimonials'
    | '/admin/activities'
    | '/admin/admissions'
    | '/admin/contact-information'
    | '/admin/dashboard'
    | '/admin/enquiries'
    | '/admin/facilities'
    | '/admin/gallery'
    | '/admin/login'
    | '/admin/programs'
    | '/admin/testimonials'
    | '/admin/website-settings'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/activities'
    | '/admissions'
    | '/contact'
    | '/day-care'
    | '/facilities'
    | '/gallery'
    | '/play-school'
    | '/programs'
    | '/testimonials'
    | '/admin/activities'
    | '/admin/admissions'
    | '/admin/contact-information'
    | '/admin/dashboard'
    | '/admin/enquiries'
    | '/admin/facilities'
    | '/admin/gallery'
    | '/admin/login'
    | '/admin/programs'
    | '/admin/testimonials'
    | '/admin/website-settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ActivitiesRoute: typeof ActivitiesRoute
  AdmissionsRoute: typeof AdmissionsRoute
  ContactRoute: typeof ContactRoute
  DayCareRoute: typeof DayCareRoute
  FacilitiesRoute: typeof FacilitiesRoute
  GalleryRoute: typeof GalleryRoute
  PlaySchoolRoute: typeof PlaySchoolRoute
  ProgramsRoute: typeof ProgramsRoute
  TestimonialsRoute: typeof TestimonialsRoute
  AdminActivitiesRoute: typeof AdminActivitiesRoute
  AdminAdmissionsRoute: typeof AdminAdmissionsRoute
  AdminContactInformationRoute: typeof AdminContactInformationRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminEnquiriesRoute: typeof AdminEnquiriesRoute
  AdminFacilitiesRoute: typeof AdminFacilitiesRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminProgramsRoute: typeof AdminProgramsRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  AdminWebsiteSettingsRoute: typeof AdminWebsiteSettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/day-care': {
      id: '/day-care'
      path: '/day-care'
      fullPath: '/day-care'
      preLoaderRoute: typeof DayCareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilities': {
      id: '/facilities'
      path: '/facilities'
      fullPath: '/facilities'
      preLoaderRoute: typeof FacilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play-school': {
      id: '/play-school'
      path: '/play-school'
      fullPath: '/play-school'
      preLoaderRoute: typeof PlaySchoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/activities': {
      id: '/admin/activities'
      path: '/admin/activities'
      fullPath: '/admin/activities'
      preLoaderRoute: typeof AdminActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/admissions': {
      id: '/admin/admissions'
      path: '/admin/admissions'
      fullPath: '/admin/admissions'
      preLoaderRoute: typeof AdminAdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/contact-information': {
      id: '/admin/contact-information'
      path: '/admin/contact-information'
      fullPath: '/admin/contact-information'
      preLoaderRoute: typeof AdminContactInformationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/enquiries': {
      id: '/admin/enquiries'
      path: '/admin/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AdminEnquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/facilities': {
      id: '/admin/facilities'
      path: '/admin/facilities'
      fullPath: '/admin/facilities'
      preLoaderRoute: typeof AdminFacilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/admin/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/programs': {
      id: '/admin/programs'
      path: '/admin/programs'
      fullPath: '/admin/programs'
      preLoaderRoute: typeof AdminProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/admin/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/website-settings': {
      id: '/admin/website-settings'
      path: '/admin/website-settings'
      fullPath: '/admin/website-settings'
      preLoaderRoute: typeof AdminWebsiteSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ActivitiesRoute: ActivitiesRoute,
  AdmissionsRoute: AdmissionsRoute,
  ContactRoute: ContactRoute,
  DayCareRoute: DayCareRoute,
  FacilitiesRoute: FacilitiesRoute,
  GalleryRoute: GalleryRoute,
  PlaySchoolRoute: PlaySchoolRoute,
  ProgramsRoute: ProgramsRoute,
  TestimonialsRoute: TestimonialsRoute,
  AdminActivitiesRoute: AdminActivitiesRoute,
  AdminAdmissionsRoute: AdminAdmissionsRoute,
  AdminContactInformationRoute: AdminContactInformationRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminEnquiriesRoute: AdminEnquiriesRoute,
  AdminFacilitiesRoute: AdminFacilitiesRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminProgramsRoute: AdminProgramsRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  AdminWebsiteSettingsRoute: AdminWebsiteSettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
